import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { TrackList } from "../components/track-list";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const tracks = api.example.getAllTracks.useQuery()
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Track<span className="text-[hsl(280,100%,70%)]">Flow</span>
          </h1>
          {/* <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"> */}
            <div

              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
            >
              <h3 className="text-2xl font-bold">Analyze tracks →</h3>
              <div className="text-lg">
                Start analyzing BPM from tracks located in your <pre>/music</pre> folder
              </div>
            </div>
          {/* </div> */}
          {tracks.isError && <p>{tracks.error.message}</p>}
          <TrackList tracks={tracks.data} />
        </div>
      </main>
    </>
  );
};

export default Home;
